
spring:
  application:
    name: ms-consumer-cashier
server:
  port: 8003
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ms-consumer-cashier-8003