spring:
  profiles:
    active: server

---
spring:
  profiles: server
server:
  port: 9000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9000/eureka/

---
spring:
  profiles: provider
  application:
    name: ms-provider-user
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ms-provider-user-8001

---
spring:
  profiles: consumer
  application:
    name: ms-consumer-user
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ms-consumer-user-8002